build:
  environment:
    php:
      version: '5.3.29'

  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run

    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit
            coverage:
              file: tests/clover.xml
              format: clover

checks:
  php: true

filter:
  excluded_paths:
    - tests/*
